import type { Metadata } from "next";
import { Dosis, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { MarketProvider } from "@/context/MarketContext";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} ${jetbrainsMono.variable} antialiased bg-[#141414] text-gray-200 selection:bg-orange-500 selection:text-white font-light`}>
        <MarketProvider>
          {/* Sidebar and Main Layout Structure matching reference App shell */}
          <div className="min-h-screen flex font-sans">
            <Sidebar />
            <main className="pl-20 w-full relative">
              {children}
            </main>
          </div>
        </MarketProvider>
      </body>
    </html>
  );
}
