"""Add SystemConfig table

Revision ID: 175382c63536
Revises: 84641e540464
Create Date: 2026-02-01 14:07:28.311307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175382c63536'
down_revision: Union[str, Sequence[str], None] = '84641e540464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_pair', sa.String(), nullable=True),
    sa.Column('selected_strategy', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('sl_percent', sa.Float(), nullable=True),
    sa.Column('tp_percent', sa.Float(), nullable=True),
    sa.Column('trailing_stop', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
